Repository hazelcast/hazelcast-csharp-client, pull requests merged in 2021-04, with the labels that each got.

#433 Adjustments for 4.2 server compatibility
  src/Hazelcast.Net.Tests/Remote/ClientMapTest.cs
  src/Hazelcast.Net.Tests/Remote/ClientTxnMapTest.cs
  src/Hazelcast.Net.Tests/Remote/ClientTxnTest.cs
  src/Hazelcast.Net.Tests/Remote/MapTests.cs
Labels: Source: Internal, Type: Enhancement

#440 Build and publish Hazelcast.Net.Win32 NuGet package
  hz.ps1
  src/Hazelcast.Net.Win32/Hazelcast.Net.Win32.csproj
  src/Hazelcast.Net.Win32/Security/Win32/AuthIdentity.cs
  src/Hazelcast.Net.Win32/Security/Win32/CredentialHandle.cs
  src/Hazelcast.Net.Win32/Security/Win32/Enums.cs
  src/Hazelcast.Net.Win32/Security/Win32/SspiContext.cs
  src/Hazelcast.Net.Win32/Security/Win32/SuppliedCredential.cs
Labels: Source: Internal, Type: Feature Request

#446 Fix hz script with UseBasicParsing
  hz.ps1
Labels: Source: Internal, Type: Enhancement

#447 Improvements to testing utilities
  Hazelcast.Net.sln.DotSettings
  src/Hazelcast.Net.Examples/Hazelcast.Net.Examples.csproj
  src/Hazelcast.Net.Testing/AssertEx.cs
  src/Hazelcast.Net.Testing/Configuration/TestingConfigurationExtensions.cs
  src/Hazelcast.Net.Testing/Hazelcast.Net.Testing.csproj
  src/Hazelcast.Net.Testing/Logging/HConsoleLoggerProvider.cs
  src/Hazelcast.Net.Testing/Logging/ITestingLoggerProvider.cs
  src/Hazelcast.Net.Testing/Logging/StringBuilderLoggerExtensions.cs
  src/Hazelcast.Net.Testing/Logging/StringBuilderLoggerProvider.cs
  src/Hazelcast.Net.Testing/Logging/TestingLogger.cs
  src/Hazelcast.Net.Testing/Logging/TestingLoggingExtensions.cs
  src/Hazelcast.Net.Testing/Protocol/ErrorsServerCodec.cs
  src/Hazelcast.Net.Testing/RemoteControllerClientExtensions.cs
  src/Hazelcast.Net/Core/HConsole.cs
  src/Hazelcast.Net/Core/HConsoleOptions.cs
  src/Hazelcast.Net/Core/HConsoleTargetOptions.cs
  src/Hazelcast.Net/HazelcastOptionsBuilder.cs
Labels: Type: Cleanup

#448 Add Client reconnection test (issue #429)
  src/Hazelcast.Net.Tests/Remote/ReconnectTests.cs
Labels: Type: Enhancement

#449 Cleanup load-balancing
  src/Hazelcast.Net.Tests/Clustering/LoadBalancingTests.cs
  src/Hazelcast.Net/Clustering/ClusterMembers.cs
  src/Hazelcast.Net/Clustering/LoadBalancing/ILoadBalancer.cs
  src/Hazelcast.Net/Clustering/LoadBalancing/LoadBalancerBase.cs
  src/Hazelcast.Net/Clustering/LoadBalancing/RandomLoadBalancer.cs
  src/Hazelcast.Net/Clustering/LoadBalancing/RoundRobinLoadBalancer.cs
  src/Hazelcast.Net/Clustering/LoadBalancing/StaticLoadBalancer.cs
Labels: Type: Cleanup

#450 Cleanup misc core classes
  src/Hazelcast.Net/Core/AsyncContext.cs
  src/Hazelcast.Net/Core/BackgroundTask.cs
  src/Hazelcast.Net/Core/FuncExtensions.cs
  src/Hazelcast.Net/Core/HConsole.cs
  src/Hazelcast.Net/Core/HConsoleTargetOptions.cs
  src/Hazelcast.Net/Core/TaskCoreExtensions.cs
Labels: Type: Cleanup

#443 Documentation for CPDistributedObjectBase.DisposeAsync
  src/Hazelcast.Net/CP/CPDistributedObjectBase.cs
Labels: Source: Internal, Type: Enhancement
