Repository hazelcast/hazelcast-csharp-client, pull requests merged in 2022-01, with the labels that each got.

#562 Deserialization desc added [API-1019]
  doc/dev/doc/sql.md
Labels: Type: Documentation, Jira

#570 Improve the `hz` script
  build/utils.ps1
  hz.ps1
Labels: Type: Infra, State: Review

#548 Metrics / cleanup, fix client type, use CSP code not CSHARP [API-996]
  doc/dev/doc/configuration/sources.md
  src/Hazelcast.Net.Examples/Client/LongRunningCloudClient.cs
  src/Hazelcast.Net.Testing/RemoteTestBase.cs
  src/Hazelcast.Net.Tests/Cloud/CloudTests.cs
  src/Hazelcast.Net.Tests/Configuration/HazelcastOptionsTests.cs
  src/Hazelcast.Net.Tests/Core/ClientVersionTests.cs
  src/Hazelcast.Net.Tests/Remote/HeartbeatTests.cs
  src/Hazelcast.Net.Tests/Resources/Java/CloudTests/Program.java
  src/Hazelcast.Net.Tests/Resources/Java/CloudTests/TestConsumer.java
  src/Hazelcast.Net/CodeAnalysisSuppressions.cs
  src/Hazelcast.Net/Core/BytesExtensions.ReadFromByteArray.cs
  src/Hazelcast.Net/Core/ClientVersion.cs
  src/Hazelcast.Net/Core/DumpCoreExtensions.cs
  src/Hazelcast.Net/HazelcastOptions.Build.cs
  src/Hazelcast.Net/HazelcastOptionsBuilder.cs
  src/Hazelcast.Net/Metrics/ClientMetricSource.cs
  src/Hazelcast.Net/Metrics/EnumerableOfMetricsExtensions.cs
  src/Hazelcast.Net/Metrics/IMetricDescriptor.cs
  src/Hazelcast.Net/Metrics/MetricDescriptor.cs
  src/Hazelcast.Net/Metrics/MetricUnit.cs
  src/Hazelcast.Net/Metrics/Metric`TValue.cs
  src/Hazelcast.Net/Metrics/MetricsCompressor.cs
  src/Hazelcast.Net/Metrics/MetricsExtensions.cs
  src/Hazelcast.Net/Metrics/MetricsPublisher.cs
  src/Hazelcast.Net/NearCaching/NearCacheOptions.cs
  src/Hazelcast.Net/NearCaching/NearCacheStatistics.cs
Labels: State: Review
