Repository hazelcast/hazelcast-csharp-client, pull requests merged in 2022-04, with the labels that each got.

#607 Backport (Metrics / cleanup, fix client type, use CSP code not CSHARP [API-1293] #548) to 5.0.z
  src/Hazelcast.Net.Examples/Client/LongRunningCloudClient.cs
  src/Hazelcast.Net.Testing/RemoteTestBase.cs
  src/Hazelcast.Net.Tests/Cloud/CloudTests.cs
  src/Hazelcast.Net.Tests/Configuration/HazelcastOptionsTests.cs
  src/Hazelcast.Net.Tests/Core/ClientVersionTests.cs
  src/Hazelcast.Net.Tests/Remote/HeartbeatTests.cs
  src/Hazelcast.Net.Tests/Resources/Java/CloudTests/Program.java
  src/Hazelcast.Net.Tests/Resources/Java/CloudTests/TestConsumer.java
  src/Hazelcast.Net/CodeAnalysisSuppressions.cs
  src/Hazelcast.Net/Core/BytesExtensions.ReadFromByteArray.cs
  src/Hazelcast.Net/Core/ClientVersion.cs
  src/Hazelcast.Net/Core/DumpCoreExtensions.cs
  src/Hazelcast.Net/HazelcastOptions.Build.cs
  src/Hazelcast.Net/HazelcastOptionsBuilder.cs
  src/Hazelcast.Net/Metrics/ClientMetricSource.cs
  src/Hazelcast.Net/Metrics/EnumerableOfMetricsExtensions.cs
  src/Hazelcast.Net/Metrics/IMetricDescriptor.cs
  src/Hazelcast.Net/Metrics/MetricDescriptor.cs
  src/Hazelcast.Net/Metrics/MetricUnit.cs
  src/Hazelcast.Net/Metrics/Metric`TValue.cs
  src/Hazelcast.Net/Metrics/MetricsCompressor.cs
  src/Hazelcast.Net/Metrics/MetricsExtensions.cs
  src/Hazelcast.Net/Metrics/MetricsPublisher.cs
  src/Hazelcast.Net/NearCaching/NearCacheOptions.cs
  src/Hazelcast.Net/NearCaching/NearCacheStatistics.cs
Labels: Type: Backport, State: Review

#598 Complex Sql Example [API-1299]
  src/Hazelcast.Net.Examples/Sql/SqlPortableExample.cs
Labels: Type: Enhancement, State: Review

#600 Readme updates
  README.md
Labels: State: Review

#613 Prepare for Compact [API-971]
  .editorconfig
  Hazelcast.Net.sln
  Hazelcast.Net.sln.DotSettings
  hz.ps1
  src/Hazelcast.Net.Testing/Conditions/ServerVersion.cs
  src/Hazelcast.Net.Testing/HazelcastClientExtensions.cs
  src/Hazelcast.Net.Testing/RemoteControllerClientExtensions.cs
  src/Hazelcast.Net.Tests/DotNet/DotNetTests.cs
  src/Hazelcast.Net.Tests/DotNet/TypeTests.cs
  src/Hazelcast.Net/Exceptions/ExceptionMessages.cs
  src/Hazelcast.Net/Properties/AssemblyInfo.cs
  src/Hazelcast.Net/debug.editorconfig
  src/Hazelcast.Net/release.editorconfig
Labels: State: Review

#554 [API-1008]ILogger usage and message strings refactored
  src/Hazelcast.Net.Benchmarks/Hazelcast.Net.Benchmarks.csproj
  src/Hazelcast.Net.Benchmarks/LoggerMessageTemplateVsEnabledCheck.cs
  src/Hazelcast.Net/Clustering/Authenticator.cs
  src/Hazelcast.Net/Clustering/ClusterConnections.cs
  src/Hazelcast.Net/Clustering/ClusterEvents.cs
  src/Hazelcast.Net/Clustering/ClusterMembers.cs
  src/Hazelcast.Net/Clustering/Heartbeat.cs
  src/Hazelcast.Net/Clustering/MemberConnection.cs
  src/Hazelcast.Net/Clustering/MemberConnectionQueue.cs
  src/Hazelcast.Net/Clustering/RetryStrategy.cs
  src/Hazelcast.Net/Clustering/StateChangeQueue.cs
  src/Hazelcast.Net/Clustering/TerminateConnections.cs
  src/Hazelcast.Net/CodeAnalysisSuppressions.cs
  src/Hazelcast.Net/DistributedObjects/DistributedObjectFactory.cs
  src/Hazelcast.Net/Metrics/ClientMetricSource.cs
  src/Hazelcast.Net/Metrics/MetricsPublisher.cs
  src/Hazelcast.Net/NearCaching/NearCacheManager.cs
  src/Hazelcast.Net/NearCaching/RepairingHandler.cs
  src/Hazelcast.Net/Networking/ConnectAddressResolver.cs
  src/Hazelcast.Net/Networking/SslLayer.cs
  src/Hazelcast.Net/Serialization/SerializationService.cs
Labels: Priority: Normal, State: Review

#611 Member list printing is limited [API-1277] [API-1278]
  src/Hazelcast.Net.Examples/SoakTests/Soak1.cs
  src/Hazelcast.Net.Tests/Clustering/MemberConnectionTests.cs
  src/Hazelcast.Net/Clustering/ClusterMembers.cs
Labels: State: Review

#604 Port from 5.0.1
  .github/workflows/build-release.yml
  .github/workflows/release-scripts.js
  .github/workflows/trigger-release.yml
  Hazelcast.Net.sln
  build/utils.ps1
  doc/latest-version
  doc/versions.md
  doc/xrefmap.yml
  hz.ps1
  hz.sh
  src/Hazelcast.Net.Examples/Client/LongRunningCloudClient.cs
  src/Hazelcast.Net/HazelcastClientFactory.cs
Labels: State: Approved

#572 Enable .NET 6 build [API-1028]
  .github/workflows/build-branch.yml
  .github/workflows/build-pr.yml
  .github/workflows/build-release.yml
  build/build.proj
  hz.ps1
  src/Hazelcast.Net.Benchmarks/Hazelcast.Net.Benchmarks.csproj
  src/Hazelcast.Net.DependencyInjection/Hazelcast.Net.DependencyInjection.csproj
  src/Hazelcast.Net.Examples/Hazelcast.Net.Examples.csproj
  src/Hazelcast.Net.Testing/Networking/SocketListener.cs
  src/Hazelcast.Net.Testing/ObservingTestBase.cs
  src/Hazelcast.Net.Testing/TestServer/Server.cs
  src/Hazelcast.Net.Testing/TestServer/ServerSocketListener.cs
  src/Hazelcast.Net.Tests/Core/SocketExtensionsTests.cs
  src/Hazelcast.Net.Tests/DotNet/AsyncTests.cs
  src/Hazelcast.Net.Tests/DotNet/ExceptionTests.cs
  src/Hazelcast.Net.Tests/Hazelcast.Net.Tests.csproj
  src/Hazelcast.Net.Tests/Messaging/ClientMessageConnectionTests.cs
  src/Hazelcast.Net.Tests/Networking/NetworkingTests.cs
  src/Hazelcast.Net.Tests/Networking/ReproduceDotNetIssues.cs
  src/Hazelcast.Net.Tests/Networking/SocketConnectionTests.cs
  src/Hazelcast.Net.Win32/Hazelcast.Net.Win32.csproj
  src/Hazelcast.Net/Clustering/MemberConnection.cs
  src/Hazelcast.Net/Core/ExceptionExtensions.cs
  src/Hazelcast.Net/Core/SocketExtensions.cs
  src/Hazelcast.Net/Hazelcast.Net.csproj
  src/Hazelcast.Net/Networking/SocketConnectionBase.cs
  src/Hazelcast.Net/Polyfills/CancellationTokenRegistrationExtensions.cs
Labels: State: Review
