Repository hazelcast/hazelcast-csharp-client, pull requests merged in 2022-06, with the labels that each got.

#626 Fix Failed Compatibility Test
  src/Hazelcast.Net.Testing/Remote/Resources.Designer.cs
  src/Hazelcast.Net.Testing/Remote/Resources.resx
  src/Hazelcast.Net.Testing/Remote/Resources/alternative.xml
  src/Hazelcast.Net.Testing/Remote/Resources/credential.xml
  src/Hazelcast.Net.Tests/Clustering/FailoverTests.cs
  src/Hazelcast.Net.Tests/Resources/HazelcastFailoverOptions.txt
Labels: Type: Defect, State: Review

#633 Fix RetryStrategy delay
  src/Hazelcast.Net.Tests/Clustering/RetryStrategyTests.cs
  src/Hazelcast.Net/Clustering/RetryStrategy.cs
Labels: Priority: Critical, State: Review

#634 Delay failed members connections
  src/Hazelcast.Net.Tests/Clustering/ConnectMembersTests.cs
  src/Hazelcast.Net/Clustering/ClusterMembers.cs
  src/Hazelcast.Net/Clustering/MemberConnectionQueue.cs
  src/Hazelcast.Net/Clustering/MemberConnectionRequest.cs
  src/Hazelcast.Net/Core/AsyncQueue.cs
Labels: State: Review

#649 `ReadStringArray` Fixed and Tests Case Enlarged [API-1413]
  src/Hazelcast.Net.Testing/TestUtils.cs
  src/Hazelcast.Net.Tests/Serialization/DataInputOutputTest.cs
  src/Hazelcast.Net.Tests/Serialization/Objects/KitchenSinkDataSerializable.cs
  src/Hazelcast.Net.Tests/Serialization/Objects/KitchenSinkPortable.cs
  src/Hazelcast.Net/Serialization/ObjectDataInput.api.cs
Labels: Priority: Critical, Type: Defect, State: Review
